// services/resumeService.js
import api from "./api";

/**
 * Generate AI Resume
 */
export const generateAIResume = async (
  userData,
  jobDescription,
  template = "modern",
  sections = null
) => {
  try {
    console.log("Generating AI Resume...", { userData, template });

    const response = await api.post("/ai-resume/generate", {
      userData,
      jobDescription,
      template,
      sections:
        sections || [
          "summary",
          "experience",
          "skills",
          "education",
          "projects",
          "achievements",
        ],
    });

    console.log("Resume generated successfully");
    return response.data;
  } catch (error) {
    console.error(
      "Resume generation error:",
      error.response?.data || error.message
    );
    throw error;
  }
};

/**
 * Generate Cover Letter
 */
export const generateCoverLetter = async (
  userData,
  jobDescription,
  companyName,
  hiringManager
) => {
  try {
    const response = await api.post("/ai-resume/generate-cover-letter", {
      userData,
      jobDescription,
      companyName,
      hiringManager,
    });

    return response.data;
  } catch (error) {
    console.error("Cover letter error:", error.response?.data || error.message);
    throw error;
  }
};

/**
 * Improve Resume Text
 */
export const improveResumeText = async (
  text,
  purpose,
  tone = "professional"
) => {
  try {
    const response = await api.post("/ai-resume/improve", {
      text,
      purpose,
      tone,
    });

    return response.data;
  } catch (error) {
    console.error(
      "Text improvement error:",
      error.response?.data || error.message
    );
    throw error;
  }
};

/**
 * Get Resume Templates
 */
export const getResumeTemplates = async () => {
  try {
    const response = await api.get("/ai-resume/templates");
    return response.data;
  } catch (error) {
    console.error("Templates error:", error.response?.data || error.message);

    // fallback templates (safe for frontend-only deploy)
    return {
      success: true,
      templates: [
        {
          id: "modern",
          name: "Modern",
          color: "from-blue-600 to-purple-600",
          icon: "💼",
        },
        {
          id: "creative",
          name: "Creative",
          color: "from-pink-500 to-rose-500",
          icon: "🎨",
        },
        {
          id: "executive",
          name: "Executive",
          color: "from-gray-700 to-gray-900",
          icon: "👔",
        },
      ],
    };
  }
};

/**
 * Export Resume as Text (client-side simulation)
 */
export const exportResumeAsPDF = (
  resumeData,
  fileName = "resume"
) => {
  const resumeContent = `
================================
AI GENERATED RESUME
================================

Name: ${resumeData.userData?.name || "Not provided"}
Generated: ${new Date().toLocaleDateString()}

PROFESSIONAL SUMMARY:
${resumeData.resume?.summary || ""}

EXPERIENCE:
${resumeData.resume?.experience || ""}

SKILLS:
${resumeData.resume?.skills || ""}

EDUCATION:
${resumeData.resume?.education || ""}

${resumeData.resume?.projects ? `PROJECTS:\n${resumeData.resume.projects}` : ""}

${
  resumeData.resume?.achievements
    ? `ACHIEVEMENTS:\n${resumeData.resume.achievements}`
    : ""
}

================================
Generated by ATS-AI Resume Builder
================================
`;

  const blob = new Blob([resumeContent], { type: "text/plain" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `${fileName}_${new Date()
    .toISOString()
    .split("T")[0]}.txt`;

  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return { success: true, message: "Resume exported as text file" };
};

/**
 * Resume Service Health Check
 */
export const checkResumeServiceHealth = async () => {
  try {
    const response = await api.get("/ai-resume/health");
    return response.data;
  } catch (error) {
    console.error(
      "Resume service health check failed:",
      error.response?.data || error.message
    );
    return { success: false, error: "Service unavailable" };
  }
};
